sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: true
node_js:
- 6
before_deploy:
- rm .npmrc
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: bFD1MdvahSImFiLZschAnia01Itff6G6khAEZ48J0VaaEg5o+OT6jBnJn91qgQGjUFyVM+siHwDz2/4aprJLB4H3oinXfvbgP/osQ6UmVQriyuZRtY1KJipqYONokLZtjVjCJeyqSlblLWXUqkeTGknjyiM2TMjQEHNqSPDBQaM=
  app: remysharp-com
  on:
    repo: remy/remysharp.com
after_deploy:
- semantic-release post
before_script:
- npm prune
after_success:
- npm run build
- npm publish
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
