sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: true
node_js:
- 4
before_deploy:
- rm .npmrc
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: aIPVnCeL1UiNb82JlNsFyp793Au8XIemhpvax1o9B+ziNJcQULsUvGMyY7SmC0adR1ZMpUSnVCQe5FkY411STorC/BZjLjux2ricYP/TT5OBYUjtOAiUT3s8vUZw848xTQK7p5Px+1W/QuqtbR6rsTlH4FBIB6+eln5P2OpeNDw=
  app: remysharp-com
  on:
    repo: remy/remysharp.com
after_deply:
- semantic-release post
before_script:
- npm prune
after_success:
- npm run build
- npm publish
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
